### ISSUE TITLE
KeyNotFoundException when no Accept-Encoding header key exists. should fallback to no compression.

### ISSUE THREAD

**Issue by eladmarg** [Shazwazza/Smidge#130]
attached logged exception:

```
System.Collections.Generic.KeyNotFoundException: The given key 'Accept-Encoding' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.AspNetCore.HttpSys.Internal.RequestHeaders.System.Collections.Generic.IDictionary<System.String,Microsoft.Extensions.Primitives.StringValues>.get_Item(String key)
   at Smidge.RequestHelper.GetClientCompression(IDictionary`2 headers)
   at Smidge.Models.RequestModel..ctor(String valueName, IUrlManager urlManager, IActionContextAccessor accessor, IRequestHelper requestHelper)
   at Smidge.Models.BundleRequestModel..ctor(IUrlManager urlManager, IActionContextAccessor accessor, IRequestHelper requestHelper, IBundleManager bundleManager)
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ServicesModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()

```

**Comment by eladmarg** [comment]
maybe #128 might solves this.
