### ISSUE TITLE
Smidge should do some validation before processing/writing a file

### ISSUE THREAD

**Issue by PhyxionNL** [Shazwazza/Smidge#171]
Example:

```
System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Website\data\Smidge\Cache\U\sw7pscd7ms4e'||''
at System.IO.FileSystem.CreateDirectory(System.String fullPath, System.Byte[] securityDescriptor)
at System.IO.Directory.CreateDirectory(System.String path)
at Smidge.Cache.PhysicalFileCacheFileSystem.WriteFileAsync(System.String filePath, System.String contents) at offset 71
at Smidge.FileProcessors.PreProcessManager.<ProcessFileImpl>d__7.MoveNext() at offset 1373
at Smidge.FileProcessors.PreProcessManager.<ProcessFile>d__6.MoveNext() at offset 328
at Smidge.FileProcessors.PreProcessManager.<ProcessAndCacheFileAsync>d__5.MoveNext() at offset 222
at Smidge.Controllers.SmidgeController.<Bundle>d__7.MoveNext() at offset 1360
```

Another example:
```sw7pscd7ms4e%' AND 2*3*8=6*8```

**Comment by Shazwazza** [comment]
Have marked as help wanted if you have time to add some validation/tests?

**Comment by PhyxionNL** [comment]
Can you create a new release for this @Shazwazza? Thanks.

**Comment by Shazwazza** [comment]
@PhyxionNL  yep, github was down for a bit on friday when i was going to publish, will do now.

**Comment by Shazwazza** [comment]
@PhyxionNL this is published https://github.com/Shazwazza/Smidge/releases/tag/v4.2.1 thanks so much for you help and patience!
