### ISSUE TITLE
Attempting to add items to the in memory directory multiple times

### ISSUE THREAD

**Issue by dc-durable** [Shazwazza/Smidge#183]
Hello,

I'm sorry there's not a huge amount to go on here as I couldn't recreate the issue locally, but using Smidge with Umbraco it looks like there are occasions where `System.InvalidOperationException: Cannot add item to the directory, as an item with the same name already exists.` is thrown when bundling. Having looked through the source, I can see in SmidgeController.cs a todo related to locking which may be related if Bundle is being called by multiple clients simultaneously?

My stack trace from the logs looks like this:

> System.InvalidOperationException: Cannot add item to the directory, as an item with the same name already exists.
   at Dazinator.Extensions.FileProviders.InMemory.Directory.FolderDirectoryItem.AddFile(IFileInfo file)
   at Dazinator.Extensions.FileProviders.InMemory.Directory.InMemoryDirectory.AddFile(String folderPath, IFileInfo file)
   at Smidge.InMemory.MemoryCacheFileSystem.WriteFileAsync(String filePath, Stream contents)
   at Smidge.Controllers.SmidgeController.CacheCompositeFileAsync(ICacheFileSystem cacheProvider, String filePath, Stream compositeStream)
   at Smidge.Controllers.SmidgeController.Bundle(BundleRequestModel bundleModel)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
... (outputs from other middleware)

Happy to answer any questions. Thank you.

**Comment by gurgendav** [comment]
I'm experiencing the same problem. @dc-durable have you been able to solve this somehow?

**Comment by DanDiplo** [comment]
I see this a lot in Umbraco sites, too. It happens on multiple sites, usually those with a lot of requests. I'd guess a concurrency issue.

`System.InvalidOperationException: Cannot add item to the directory, as an item with the same name already exists.
   at Dazinator.Extensions.FileProviders.InMemory.Directory.FolderDirectoryItem.AddFile(IFileInfo file)
   at Dazinator.Extensions.FileProviders.InMemory.Directory.InMemoryDirectory.AddFile(String folderPath, IFileInfo file)
   at Smidge.InMemory.MemoryCacheFileSystem.WriteFileAsync(String filePath, Stream contents)
   at Smidge.Controllers.SmidgeController.CacheCompositeFileAsync(ICacheFileSystem cacheProvider, String filePath, Stream compositeStream)
   at Smidge.Controllers.SmidgeController.Bundle(BundleRequestModel bundleModel)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)`

**Comment by Shazwazza** [comment]
If anyone has time, I'd suggest just looking here as per the stack trace: Smidge.InMemory.MemoryCacheFileSystem.WriteFileAsync
Maybe its just a simple key check

**Comment by nathanfeeney** [comment]
I have noticed this issue occuring after upgrading to Umbraco 13.7.1 on a uSkinned site - in checking this issue i noticed in the last few upgrades Smidge.InMemory was remaining at version 4.4.0 but the rest of the packages were on the latest 4.5.1. Could this cause the above issue?
