### ISSUE TITLE
Integration with Castle Windsor

### ISSUE THREAD

**Issue by gabrielrobert** [Shazwazza/Smidge#50]
Hey,

I'm trying to implement Smidge in my application. When page load, I have this errors on file:

```
Castle.MicroKernel.ComponentNotFoundException: No component for supporting the service Smidge.Controllers.SmidgeController was found
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, IDictionary arguments, IReleasePolicy policy)
   at Castle.Windsor.MsDependencyInjection.ScopedWindsorServiceProvider.GetServiceInternal(Type serviceType, Boolean isOptional)
   at Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactory.CreateController(ControllerContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAllActionFiltersAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeExceptionFilterAsync>d__25.MoveNext()
```

Any idea? Thank you!

**Comment by Shazwazza** [comment]
Hi, sorry for not getting back to you on this - time has not been very good to me lately. Did you find a solution?
